### ISSUE TITLE
what is train.json and val.json

### ISSUE THREAD

**Issue by basaltzhang** [facebookresearch/low-shot-shrink-hallucinate#1]
This project is really awesome and while I was running the step two, I found two unknown files.
Could you guys tell me how to get the 
`/mnt/vol/gfsai-east/ai-group/users/bharathh/imagenet_meta/train.json`
file in _train_save_data.yaml_
and 
`/mnt/vol/gfsai-east/ai-group/users/bharathh/imagenet_meta/val.json`
file in _val_save_data.yaml_?
pretty thanks

**Comment by basaltzhang** [comment]
After reading the code, I realize the train.json and val.json are the train/val set of ImageNet, json format dict in which contains two items, 
```
{
    "image_names": list of image path, group by folder sequence of label_names item in base_classes_val_meta.json,
    "image_labels": list of image label, same length with image_names
}
```

**Comment by alono88** [comment]
@basaltzhang, 
I'm currently facing the same issue. Did you create those files yourself?
