### ISSUE TITLE
Missing val.json and train.json

### ISSUE THREAD

**Issue by haofusheng** [facebookresearch/low-shot-shrink-hallucinate#2]
Hi, I'm following your work.

In the second step 'Save features from the ConvNet', the configuration is train_save_data.yaml or val_save_data.yaml. However, I did not find '/mnt/vol/gfsai-east/ai-group/users/bharathh/imagenet_meta/train.json' and '/mnt/vol/gfsai-east/ai-group/users/bharathh/imagenet_meta/val.json'.

It seems that the order of the extracted features matters as the splitfile_{:d} specifies the order of indexes. 

Or the order of the features is irrelevant？

Thank you very much！

**Comment by rbgirshick** [comment]
@bharath272 Can you look into this when you get a chance? Thanks!

**Comment by rbgirshick** [comment]
@haofusheng: this should be addressed by 3ed5827. Please let us know if you have any issues after updating.

**Comment by haofusheng** [comment]
Thank you very much!

My issues have been addressed.
